#!/usr/bin/env sh
# _          _ _            _   _ 
#| |__  _ __(_) |_ ___  ___| |_| |
#| '_ \| '__| | __/ _ \/ __| __| |
#| |_) | |  | | ||  __/ (__| |_| |
#|_.__/|_|  |_|\__\___|\___|\__|_|
#
#Dependencies - xbacklight, dunst               

NOTIFY_ID=3000

Notify(){
	brite=`xbacklight -get`
	brite=${brite%.*}
	#bar=$(seq -s "─" $(($brite / 5)) | sed 's/[0-9]//g')
	dunstify -u normal -r $NOTIFY_ID -a "Brightness $brite%" -t 3000 " "
}

case $1 in 
	up)
		xbacklight -inc 5
		$(Notify);;
	down)
		xbacklight -dec 5
		$(Notify);;
esac

