#!/usr/bin/env sh
# _____                 _ _
#| ____|_ __ ___   ___ (_|_)
#|  _| | '_ ` _ \ / _ \| | |
#| |___| | | | | | (_) | | |
#|_____|_| |_| |_|\___// |_|
#                    |__/
# ____       _           _
#/ ___|  ___| | ___  ___| |_ ___  _ __
#\___ \ / _ \ |/ _ \/ __| __/ _ \| '__|
# ___) |  __/ |  __/ (__| || (_) | |
#|____/ \___|_|\___|\___|\__\___/|_|
#
#Allows for an emoji to be selected from anywhere
#in the desktop and copies it to clipboard.
#
#Dependencies - Dmenu, xclip, dunst/notify-send

clip=/usr/bin/xclip
notif=/usr/bin/notify-send
filepath=$HOME/DotFiles/unicodeEmojis

#emoji=$(awk '{gsub("(; U+.*)+","")} {print $0}' $filepath | dmenu -i -l 10 -p 'Pick : ' | awk '{print $1}' )
emoji=$(cut -d ';' -f1 $filepath | dmenu -i -l 10 -p 'Pick : ' | awk '{print $1}' )

[ $emoji = '' ] && $notif "Nothing in Selection" -u "normal" -t 1000 -a "System 💻" && exit
echo $emoji | tr -d '\n' | $clip -selection clipboard

[ $? -eq 0 ] && $notif "$emoji" "Copied to Clipboard." -u "normal" -t 3000 -a "System 💻"

