#!/usr/bin/env sh
# _____      _ _   
#| ____|_  _(_) |_ 
#|  _| \ \/ / | __|
#| |___ >  <| | |_ 
#|_____/_/\_\_|\__|
#  ___                       _   _                 
# / _ \ _ __   ___ _ __ __ _| |_(_) ___  _ __  ___ 
#| | | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __|
#| |_| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \
# \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/
#      |_|                                         
#
#Dependencies - dmenu[promptUser], slock

prompt=$HOME/bin/promptUser
operation=$(echo -e " Lock Screen\n Logout\n Reboot\n Shutdown" | 
	dmenu -i -l 5 | sed -E 's/$[ \t]*//g')

[ -z "$operation" ] && exit 1

case $operation in
	" Logout") 
		$prompt " Exit Current Session?"
		[ $? -eq 0 ] && $(pkill -kill -u $USER);;
	" Reboot") 
		$prompt " Reboot System?"
		[ $? -eq 0 ] && $(reboot);;
	" Shutdown")
		$prompt " ShutDown Now?"
		[ $? -eq 0 ] && $(shutdown now);;
	" Suspend")
		$prompt " Suspend All Operations?"
		[ $? -eq 0 ] && $(systemctl suspend);;
	" Lock Screen")
		$prompt " Suspend All Operations?"
		[ $? -eq 0 ] && $(slock & systemctl suspend);;
	*)
		exit 1;;
esac

