#!/usr/bin/env sh
# _____      _ _   
#| ____|_  _(_) |_ 
#|  _| \ \/ / | __|
#| |___ >  <| | |_ 
#|_____/_/\_\_|\__|
#  ___                       _   _                 
# / _ \ _ __   ___ _ __ __ _| |_(_) ___  _ __  ___ 
#| | | | '_ \ / _ \ '__/ _` | __| |/ _ \| '_ \/ __|
#| |_| | |_) |  __/ | | (_| | |_| | (_) | | | \__ \
# \___/| .__/ \___|_|  \__,_|\__|_|\___/|_| |_|___/
#      |_|                                         
#
#Dependencies - dmenu[promptUser], slock

PROMPT=$HOME/bin/promptUser
OPERATION=$(echo -e " Lock Screen\n Suspend\n Logout\n Reboot\n Shutdown" | 
	dmenu -i -l 5 | sed -E 's/$[ \t]*//g')

[ -z "$OPERATION" ] && exit 1

case $OPERATION in
	" Logout") 
		$PROMPT " Exit Current Session?"
		[ $? -eq 0 ] && pkill -kill -u $USER;;
	" Reboot") 
		$PROMPT " Reboot System?"
		[ $? -eq 0 ] && reboot;;
	" Shutdown")
		$PROMPT " ShutDown Now?"
		[ $? -eq 0 ] && shutdown now;;
	" Suspend")
		$PROMPT " Suspend All Operations?"
		[ $? -eq 0 ] && sleep 0.25s; slock & systemctl suspend;;
	" Lock Screen")
		$PROMPT " Suspend All Operations?"
		[ $? -eq 0 ] && sleep 0.25s; slock;;
	*)
		exit 1;;
esac

