#!/usr/bin/env sh
#       _                           _   _ 
# _ __ | | __ _ _   _  ___ _ __ ___| |_| |
#| '_ \| |/ _` | | | |/ _ \ '__/ __| __| |
#| |_) | | (_| | |_| |  __/ | | (__| |_| |
#| .__/|_|\__,_|\__, |\___|_|  \___|\__|_|
#|_|            |___/                     
#
#Dependencies - mpc/mpd, dunst

NOTIFY_ID=3000
i_PLAY=" 契"
i_PAUSE=" "

Notify(){
	status=`mpc status`
	# track=`mpc -q current | cut -d "." -f1`
	if [ -z "$status" ]; then
		dunstify -u normal -r $NOTIFY_ID -t 3000 -a "Nothing in Queue," "Bailing..."
	else
		$(echo $status | grep -E '\[paused\]' > /dev/null) && status="$i_PAUSE Paused" ||
			status="$i_PLAY Now Playing"
		dunstify -u normal -r $NOTIFY_ID -t 3000 -a "$status" "$(mpc -q --format '%title%\n%album%\n%performer%' current)"
	fi
}

CheckInstance(){
	# [ ! -s "$XDG_CONFIG_HOME/mpd/pid" ] && mpd &
	pgrep mpd > /dev/null || mpd &
}

case $1 in
	toggle|prev|next)
		$(CheckInstance)
		mpc -q $1
		$(Notify);;
	*)
		dunstify -u normal -r $NOTIFY_ID -t 3000 -a "Unknown Player Option," "Bailing...";;
esac




