#!/usr/bin/env sh
#                            _           
# _ __ ___  ___ ___  _ __ __| | ___ _ __ 
#| '__/ _ \/ __/ _ \| '__/ _` |/ _ \ '__|
#| | |  __/ (_| (_) | | | (_| |  __/ |   
#|_|  \___|\___\___/|_|  \__,_|\___|_|   
#                                        
#Dependencies - ffmpeg, pulseaudio

dest="$HOME/Library/Videos"
SIZE="1366x768"
DEFAULT="-framerate 60 -preset ultrafast -crf 0"
AUDIO=""

[ ! -d "$dest" ] && mkdir -p "$dest"
cd $dest
case $1 in
	"screenNS")
		file="ScreenGrab_$(date +%d%m%y_%H%M%S).mp4"
		VIDEO="-video_size $SIZE -f x11grab -i :0.0"
		;;
	"screenS")
		file="ScreenGrab_$(date +%d%m%y_%H%M%S).mp4"
		VIDEO="-video_size $SIZE -f x11grab -i :0.0"
		AUDIO="-f pulse -i default"
		;;
	"cam")
		file="Rec_$(date +%d%m%y_%H%M%S).mp4"
		VIDEO="-i /dev/video0"
		AUDIO="-f pulse -i default"
		;;
	*)
		exit 1;;
esac

file="$dest/$file"
ffmpeg $VIDEO $AUDIO $DEFAULT $file

