#!/usr/bin/env sh
#                            _           
# _ __ ___  ___ ___  _ __ __| | ___ _ __ 
#| '__/ _ \/ __/ _ \| '__/ _` |/ _ \ '__|
#| | |  __/ (_| (_) | | | (_| |  __/ |   
#|_|  \___|\___\___/|_|  \__,_|\___|_|   
#                                        
#Dependencies - ffmpeg, pulseaudio, dunst, dmenu


NOTIFY_ID=3000
Record(){
	DEST="$HOME/Library/Videos"
	SIZE="1366x768"
	DEFAULT="-framerate 60 -preset ultrafast -crf 0"

	[ ! -d "$DEST" ] && mkdir -p "$DEST"
	cd $DEST

	castType=$(echo -e "Camera\nScreen\nScreen with Audio" | dmenu -i -l 5 -p " " | sed -E 's/[ \t]*$//g' )
	case $castType in
		"Screen")
			FILE="ScreenGrab_$(date +%d%m%y_%H%M%S).mp4"
			VIDEO="-video_size $SIZE -f x11grab -i $DISPLAY"
			TYPE="Recording Screen..."
			;;
		"Screen with Audio")
			FILE="ScreenGrab_$(date +%d%m%y_%H%M%S).mp4"
			VIDEO="-video_size $SIZE -f x11grab -i $DISPLAY"
			AUDIO="-f pulse -i default"
			TYPE="Recording Screen with Audio..."
			;;
		"Camera")
			FILE="Rec_$(date +%d%m%y_%H%M%S).mp4"
			VIDEO="-i /dev/video0"
			AUDIO="-f pulse -i default"
			TYPE="Recording Through Cam..."
			;;
		*)
			dunstify -u normal -r $NOTIFY_ID -a "Recorder" -t 3000 "Bailing..."
			exit 1;;
	esac

	FILE="$DEST/$FILE"
	dunstify -u normal -r $NOTIFY_ID -a "Recorder " -t 3000 "$TYPE"

	ffmpeg $VIDEO $AUDIO $DEFAULT $FILE
	if [ ! $? -eq 0 ] && [ -e $FILE ]; then
		dunstify -u normal -r $NOTIFY_ID -a "Recorder" -t 3000 "Video Saved to Library."
	else
		dunstify -u critical -r $NOTIFY_ID -a "Recorder" -t 3000 "Something's Wrong," "Bailing..."
	fi
}

# checkInstance(){
toggle(){
	if $(pgrep ffmpeg > /dev/null); then
		killall ffmpeg;
		exit 0
	else
		$(Record)
	fi
}

# $(checkInstance)
$(toggle)

