#!/usr/bin/env sh

BACKUPDIR="$XDG_DATA_HOME/pkgs"
PACPKGS="$BACKUPDIR/pacPkgs.bak"
AURPKGS="$BACKUPDIR/aurPkgs.bak"

backup(){
	[ ! -d "$BACKUPDIR" ] && mkdir -p "$BACKUPDIR"
	cd $BACKUPDIR

	pacman -Qentq > $PACPKGS
	pacman -Qemtq > $AURPKGS
}

restore(){
	[ "$(ping -c1 1.1)" > /dev/null ] || exit 1
	[ ! -d "$BACKUPDIR" ] && exit 1

	[ -e "$PACPKGS" ] && sudo pacman -S --needed - < $PACPKGS

	if [ -e "$AURPKGS" ]; then
		[ "$(pacman -Qs yay)" > /dev/null ] || $(instl_helper)
		[ "$?" -eq 0 ] && yay -S --needed < $AURPKGS
	fi
}

instl_helper(){
	sudo pacman -Syu git base-devel
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
	cd ..
}

case $1 in
	backup|restore) $($1);;
	*)
		echo -e "Unknown Option...\nBailing..."
		exit 1;;
esac

