#!/usr/bin/env sh
#  ____
# | __ ) _ __ _____      _____  ___ _ __
# |  _ \| '__/ _ \ \ /\ / / __|/ _ \ '__|
# | |_) | | | (_) \ V  V /\__ \  __/ |
# |____/|_|  \___/ \_/\_/ |___/\___|_|
#
# Surfs the internet for a given text/ Query using the default search engine or
# directly opens a provided URL.
# To directly add Bookmarks, Just add the URLs below.
#
# Dependencies: dmenu.

FLAGS="--new-window"
DEFURL="https://duckduckgo.com/?q="
#URL=$(dmenu -i -p "Which URL to Follow?" <&-)
URL=$(echo -e "                                        "\
	"\n Archives"\
	"\nDevDocs"\
	"\nAlgorithms"\
	"\n GitHub"\
	"\n Google"\
	"\n Reddit"\
	"\nPrivacyTools"\
	"\n縷 RegExr"\
	"\n Twitter"\
	"\n YouTube" | dmenu -i -l 5 -p "   " | sed -E 's/[ \t]*$//g')

case $URL in
	" Archives")	URL='https://archive.org';;
	"DevDocs")		URL='https://devdocs.io';;
	"Algorithms")	URL="https://the-algorithms.com";;
	" GitHub") 	URL='https://github.com';;
	" Google") 	URL='https://google.com';;
	"PrivacyTools")	URL="https://privacytools.io";;
	" Reddit") 	URL='https://reddit.com';;
	"縷 RegExr") 	URL='https://regexr.com';;
	" Twitter") 	URL='https://twitter.com';;
	" YouTube") 	URL='https://youtube.com';;
	*)
		[ -z $URL ] && exit 1	
		[ ! $(echo $URL | grep -E '\.(com|org|net|in|io)') ] \
			&& URL=$(echo "${DEFURL}${URL}" | sed 's/ /+/g')
			
		[ ! $(echo $URL | grep -E 'https') ] && URL=$(echo "https://${URL}" | sed 's/ //g');;
esac

[ -n "$URL" ] && $BROWSER $FLAGS $URL

