#!/usr/bin/env sh
# ____
#| __ ) _ __ _____      _____  ___ _ __
#|  _ \| '__/ _ \ \ /\ / / __|/ _ \ '__|
#| |_) | | | (_) \ V  V /\__ \  __/ |
#|____/|_|  \___/ \_/\_/ |___/\___|_|
#
#Surfs the internet for a given text/ Query using the default search engine or
#directly opens a provided URL.
#To directly add Bookmarks, Just add the URLs below.
#
#Dependencies -> dmenu.

flags="--new-window"
defURL="https://duckduckgo.com/?q="
#url=$(dmenu -i -p "Which URL to Follow?" <&-)
url=$(echo -e "                                        "\
	"\nArchives"\
	"\nDevDocs"\
	"\nGitHub"\
	"\nGoogle"\
	"\nMangaPark"\
	"\nReddit"\
	"\nPrivacyTools"\
	"\nRegExr"\
	"\nTwitter"\
	"\nYouTube" | dmenu -i -l 5 -p "URL : " | sed -E 's/[ \t]*$//g')

case $url in
	"Archives")	url='https://archive.org';;
	"DevDocs") 	url='https://devdocs.io';;
	"GitHub") 	url='https://github.com/login';;
	"Google") 	url='https://google.com';;
	"MangaPark") 	url='https://mangapark.net';;
	"PrivacyTools")	url="https://privacytools.io";;
	"Reddit") 	url='https://reddit.com/login';;
	"RegExr") 	url='https://regexr.com';;
	"Twitter") 	url='https://twitter.com/login';;
	"YouTube") 	url='https://youtube.com/signin';;
	*)
		[ -z $url ] && exit 1	
		[ ! $(echo $url | grep -E '\.(com|org|net|in|io)') ] \
			&& url=$(echo "${defURL}${url}" | sed 's/ /+/g')
			
		[ ! $(echo $url | grep -E 'https') ] && url=$(echo "https://${url}" | sed 's/ //g');;
esac

[ -n "$url" ] && $BROWSER $flags $url

