#!/usr/bin/env sh
# ____                              ____            _
#/ ___|  ___ _ __ ___  ___ _ __    / ___|__ _ _ __ | |_ _   _ _ __ ___
#\___ \ / __| '__/ _ \/ _ \ '_ \  | |   / _` | '_ \| __| | | | '__/ _ \
# ___) | (__| | |  __/  __/ | | | | |__| (_| | |_) | |_| |_| | | |  __/
#|____/ \___|_|  \___|\___|_| |_|  \____\__,_| .__/ \__|\__,_|_|  \___|
#                                            |_|
#
#Captures a screenshot of the screen and saves it to ~/Pictures/Screenshots.
#The destination directory is created if it doesn't exist.
#
#Dependencies -> scrot, dunst, notify-send

filename="Screenshot_$(date +%Y%m%d_%H%M%S).png"
dest=$HOME/Media/Pictures/Screenshots
shot=/usr/bin/scrot
notif=/usr/bin/notify-send

#[ -e ~/Pictures ] || mkdir ~/Pictures
[ -e $dest ] || mkdir -p $dest
#[ "$1" = "full" ] && flags='-q 100'
#[ "$1" = "selective" ] && flags='-s -q 100'
if [ "$1" = "full" ]; then
	flags='-q 100'
else
	flags='-s -q 100'
fi

#$shot $flags $filename && mv -f ./${filename} $Dest
$shot $flags $filename
if [ $? -eq 0 ]; then
	mv -f ./${filename} $dest
	$notif $filename "ScreenShot saved." -u "normal" -t 3000 -a "System 💻"
else
	$notif "ScreenShot Capture Failed" -u "critical" -t 3000 -a "System 💻"
fi
