#!/usr/bin/env sh
# ____                              ____            _
#/ ___|  ___ _ __ ___  ___ _ __    / ___|__ _ _ __ | |_ _   _ _ __ ___
#\___ \ / __| '__/ _ \/ _ \ '_ \  | |   / _` | '_ \| __| | | | '__/ _ \
# ___) | (__| | |  __/  __/ | | | | |__| (_| | |_) | |_| |_| | | |  __/
#|____/ \___|_|  \___|\___|_| |_|  \____\__,_| .__/ \__|\__,_|_|  \___|
#                                            |_|
#
#Captures a screenshot of the screen and saves it to ~/Pictures/Screenshots.
#
#Dependencies -> scrot, dunst, notify-send

filename="Screenshot_$(date +%Y%m%d_%H%M%S).png"
dest=$HOME/Media/Pictures/Screenshots

[ -e $dest ] || mkdir -p $dest
cd $dest

[ "$1" = "full" ] && flags='-q 100' || flags='-s -q 100'

scrot $flags $filename
[ ! $? -eq 0 ] && dunstify -u "critical" -t 3000 -a "System 💻" "Capture Failed" || 
	dunstify -u "normal" -t 3000 -a "System  " "$filename" "Screenshot Saved"

