#!/usr/bin/env sh 
#
#__   __          _         _          
#\ \ / /__  _   _| |_ _   _| |__   ___ 
# \ V / _ \| | | | __| | | | '_ \ / _ \
#  | | (_) | |_| | |_| |_| | |_) |  __/
#  |_|\___/ \__,_|\__|\__,_|_.__/ \___|
#                                      
# ____                      _                 _           
#|  _ \  _____      ___ __ | | ___   __ _  __| | ___ _ __ 
#| | | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__|
#| |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   
#|____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   
# 
#Simple Program to download Video/Audio(s) from Youtube or other such servies.
#
#Dependencies - youtube-dl, dmenu[promptUser], dunst/notify-send

prompt=$HOME/bin/promptUser
dest=$HOME/Media/YTDownloads
url=$(xclip -selection primary -o)

[ -e $dest ] || mkdir -p $dest
cd $dest

[ -z "$url" ] && dunstify -u "normal" -t 3000 -a " Downloader" "Nothing to do," "Bailing..." && exit 1
# [ ! $(echo $url | grep -E '\.(com|org|net|in)') ] && dunstify -u "critical" -t 3000 \
# 	-a " Downloader" "Invalid Url" && exit 1
[ ! $(echo $url | grep -E '(((http|https):\/\/|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./&%?=_-]*)') ] &&
		dunstify -u "critical" -t 10000 -a " Downloader" "Invalid Url" && exit 1

[ $(echo $url | grep 'list') ] && 
	options="Download playlist\nDownload current video\nExtract audio from playlist\nExtract audio from current video" ||
	options="Download video\nExtract audio from video" 

format=$(echo -e $options | dmenu -i -l 5 -p "Select a Download Format : " | sed -E 's/[ \t]*$//g')

case $format in
	"Extract audio from playlist") 
		url=$(echo $url | cut -d "&" -f1-2)
		flags=" -xq --no-warnings --audio-format mp3 --audio-quality 0";;
	"Download playlist") 
		url=$(echo $url | cut -d "&" -f1-2)
		flags=" -q --no-warnings --format mp4 --audio-format mp3 --audio-quality 0";;
	"Extract audio from video")
		url=$(echo $url | cut -d "&" -f1)
		flags=" -xq --no-warnings --audio-format mp3 --audio-quality 0";;
	"Download video") 
		url=$(echo $url | cut -d "&" -f1)
		flags=" -q --no-warnings --format mp4 --audio-format mp3 --audio-quality 0";;
	*)
		dunstify -u "normal" -t 3000 -a " Downloader" "Nothing to do," "Bailing..."
		exit ;;
esac

title=$(youtube-dl --get-title $url)

[ -z "$title" ] && dunstify -u "critical" -t 3000 -a " Downloader" "Something's Wrong," "Bailing..." && 
	exit 1

dunstify -u "normal" -t 3000 -a " Downloader" "$title" "Download Started"

youtube-dl $flags $url
[ $? -eq 0 ] && dunstify -u "normal" -t 3000 -a " Downloader" "$title" "Download Complete" || 
	dunstify -u "critical" -t 3000 -a "  Downloader" "$title" "Download Failed"

