#!/usr/bin/env sh 
#
#__   __          _         _          
#\ \ / /__  _   _| |_ _   _| |__   ___ 
# \ V / _ \| | | | __| | | | '_ \ / _ \
#  | | (_) | |_| | |_| |_| | |_) |  __/
#  |_|\___/ \__,_|\__|\__,_|_.__/ \___|
#                                      
# ____                      _                 _           
#|  _ \  _____      ___ __ | | ___   __ _  __| | ___ _ __ 
#| | | |/ _ \ \ /\ / / '_ \| |/ _ \ / _` |/ _` |/ _ \ '__|
#| |_| | (_) \ V  V /| | | | | (_) | (_| | (_| |  __/ |   
#|____/ \___/ \_/\_/ |_| |_|_|\___/ \__,_|\__,_|\___|_|   
# 
#Simple Program to download Video/Audio(s) from Youtube or any other such servies.
#
#Dependencies - youtube-dl, dunst/notify-send

URL=$(xclip -selection primary -o)

[ -z "$URL" ] && dunstify -u "normal" -t 3000 -a " Downloader" "Nothing to do," "Bailing..." && exit 1

[ ! $(echo $URL | grep -E '(((http|https):\/\/|www\\.)[a-zA-Z0-9.]*[:]?[a-zA-Z0-9./&%?=_-]*)') ] &&
		dunstify -u "critical" -t 10000 -a " Downloader" "Invalid Url" && exit 1

[ $(echo $URL | grep 'list') ] && 
	OPTS="Download playlist\nDownload video\nExtract audio from playlist\nExtract audio" ||
	OPTS="Download video\nExtract audio" 

format=$(echo -e $OPTS | dmenu -i -l 5 -p "Select a Download Format : " | sed -E 's/[ \t]*$//g')
case $format in
	"Extract audio from playlist") 
		URL=$(echo $URL | cut -d "&" -f1-2)
		FLAGS=" -x";;
	"Download playlist") 
		URL=$(echo $URL | cut -d "&" -f1-2);;
	"Extract audio")
		URL=$(echo $URL | cut -d "&" -f1)
		FLAGS=" -x";;
	"Download video") 
		URL=$(echo $URL | cut -d "&" -f1);;
	*)
		dunstify -u "normal" -t 3000 -a " Downloader" "Nothing to do," "Bailing..."
		exit ;;
esac

TITLE=$(youtube-dl --get-title $URL)

[ -z "$TITLE" ] && dunstify -u "critical" -t 3000 -a " Downloader" "Something's Wrong," "Bailing..." && 
	exit 1

dunstify -u "normal" -t 3000 -a " Downloader" "$TITLE" "Download Started"

youtube-dl $FLAGS $URL
[ $? -eq 0 ] && dunstify -u "normal" -t 3000 -a " Downloader" "$TITLE" "Download Complete" || 
	dunstify -u "critical" -t 3000 -a "  Downloader" "$TITLE" "Download Failed"

